players:
  - name: git
    args: [a]
    git:
      repo: https://github.com/dchiquito/boom-and-zoom
      target: main
    build: cargo build --bin baz_cli --release
    artifact: target/release/baz_cli
  - name: random
    args: ["play", "random"]
    workdir: ../cli/
    build: cargo build --release
    artifact: ../target/release/baz_cli
  - name: random-forward
    args: ["play", "random-forward"]
    workdir: ../cli/
    build: cargo build --release
    artifact: ../target/release/baz_cli
  - name: go-fast
    args: ["play", "go-fast"]
    workdir: ../cli/
    build: cargo build --release
    artifact: ../target/release/baz_cli
  - name: go-faster
    args: ["play", "go-faster"]
    workdir: ../cli/
    build: cargo build --release
    artifact: ../target/release/baz_cli
  - name: genius
    args: ["play", "genius"]
    workdir: ../cli/
    build: cargo build --release
    artifact: ../target/release/baz_cli
tournament:
  - random
  - random-forward
  - go-fast
  - go-faster
  - genius
