players:
  - name: foo
    args: a
    git:
      repo: https://github.com/dchiquito/boom-and-zoom
      target: main
    build: cargo build --bin baz_cli --release
    artifact: target/release/baz_cli
  - name: bar
    args:
    workdir: ../cli/
    build: cargo build --release
    artifact: ../target/release/baz_cli
tournament:
  - foo
  - bar
